import { createClient } from '@supabase/supabase-js'
import { assertPeriodOpen, postJournalEntry, JournalPostingError } from './post-journal-entry'

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

async function generateInvoiceNumber(tenantId: string): Promise<string> {
  const year = new Date().getFullYear()
  const { count } = await supabaseAdmin
    .from('invoices')
    .select('id', { count: 'exact', head: true })
    .eq('tenant_id', tenantId)
  return `INV-${year}-${String((count || 0) + 1).padStart(4, '0')}`
}

export class InvoiceCreationError extends Error {
  status: number
  constructor(message: string, status = 400) {
    super(message)
    this.status = status
  }
}

export type CreateInvoiceInput = {
  tenantId: string
  matterId: string
  dueDate?: string | null
  timeEntryIds?: string[]
  disbursementIds?: string[]
  createdBy?: string | null
  autoGenerated?: boolean
}

// Shared by the manual "Create Invoice" route (POST /api/accounttrack/invoices)
// and BillTrack's Stage 2 auto-generation cron — one code path for turning
// unbilled time entries/disbursements into an invoice + GL entry, so the two
// callers can never drift out of sync on the accounting logic.
export async function createInvoiceForMatter(input: CreateInvoiceInput) {
  const entryIds = input.timeEntryIds || []
  const disbIds = input.disbursementIds || []

  if (entryIds.length === 0 && disbIds.length === 0) {
    throw new InvoiceCreationError('Select at least one time entry or disbursement to bill')
  }

  const [entriesRes, disbursementsRes] = await Promise.all([
    entryIds.length > 0
      ? supabaseAdmin
          .from('time_entries')
          .select('id, amount_usd')
          .eq('tenant_id', input.tenantId)
          .eq('matter_id', input.matterId)
          .eq('billable', true)
          .in('status', ['draft', 'submitted'])
          .in('id', entryIds)
      : Promise.resolve({ data: [] as { id: string; amount_usd: number }[] }),
    disbIds.length > 0
      ? supabaseAdmin
          .from('disbursements')
          .select('id, amount_usd')
          .eq('tenant_id', input.tenantId)
          .eq('matter_id', input.matterId)
          .eq('billed', false)
          .in('id', disbIds)
      : Promise.resolve({ data: [] as { id: string; amount_usd: number }[] }),
  ])

  const entries = entriesRes.data || []
  const disbursements = disbursementsRes.data || []

  if (entries.length === 0 && disbursements.length === 0) {
    throw new InvoiceCreationError('None of the selected items are still unbilled')
  }

  const feesAmount = entries.reduce((sum, e) => sum + Number(e.amount_usd || 0), 0)
  const disbursementsAmount = disbursements.reduce((sum, d) => sum + Number(d.amount_usd || 0), 0)
  const invoiceNumber = await generateInvoiceNumber(input.tenantId)
  const invoiceDate = new Date().toISOString().split('T')[0]

  try {
    await assertPeriodOpen(input.tenantId, invoiceDate)
  } catch (err) {
    if (err instanceof JournalPostingError) throw new InvoiceCreationError(err.message, 400)
    throw err
  }

  const { data: invoice, error: invoiceError } = await supabaseAdmin
    .from('invoices')
    .insert({
      tenant_id: input.tenantId,
      matter_id: input.matterId,
      invoice_number: invoiceNumber,
      invoice_date: invoiceDate,
      due_date: input.dueDate || null,
      fees_amount_usd: feesAmount,
      disbursements_amount_usd: disbursementsAmount,
      total_amount_usd: feesAmount + disbursementsAmount,
      status: 'open',
      created_by: input.createdBy || null,
      auto_generated: input.autoGenerated || false,
    })
    .select()
    .single()

  if (invoiceError || !invoice) {
    throw new InvoiceCreationError(invoiceError?.message || 'Failed to create invoice', 500)
  }

  try {
    await postJournalEntry({
      tenantId: input.tenantId,
      entryDate: invoiceDate,
      description: `Invoice ${invoiceNumber} created`,
      sourceType: 'invoice_created',
      sourceId: invoice.id,
      createdBy: input.createdBy || invoice.created_by,
      lines: [
        { accountKey: 'accounts_receivable', matterId: input.matterId, debitUsd: feesAmount + disbursementsAmount },
        { accountKey: 'fees_earned', matterId: input.matterId, creditUsd: feesAmount },
        { accountKey: 'client_costs_advanced', matterId: input.matterId, creditUsd: disbursementsAmount },
      ],
    })
  } catch (err) {
    throw new InvoiceCreationError(`Invoice created but GL posting failed: ${(err as Error).message}`, 500)
  }

  if (entries.length > 0) {
    await supabaseAdmin
      .from('time_entries')
      .update({ status: 'billed', invoice_id: invoice.id })
      .in('id', entries.map((e) => e.id))
  }

  if (disbursements.length > 0) {
    await supabaseAdmin
      .from('disbursements')
      .update({ billed: true, invoice_id: invoice.id })
      .in('id', disbursements.map((d) => d.id))
  }

  return invoice
}
