import { createClient } from '@supabase/supabase-js'
import { assertPeriodOpen, postJournalEntry, JournalPostingError, type JournalLineInput } from './post-journal-entry'
import { getExchangeRate, ExchangeRateError } from './exchange-rate'
import { tagOriginalAmount, tagOriginalAmountById } from './tag-original-amount'

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

async function generateInvoiceNumber(tenantId: string): Promise<string> {
  const year = new Date().getFullYear()
  const { count } = await supabaseAdmin
    .from('invoices')
    .select('id', { count: 'exact', head: true })
    .eq('tenant_id', tenantId)
  return `INV-${year}-${String((count || 0) + 1).padStart(4, '0')}`
}

export class InvoiceCreationError extends Error {
  status: number
  constructor(message: string, status = 400) {
    super(message)
    this.status = status
  }
}

export type CreateInvoiceInput = {
  tenantId: string
  matterId: string
  dueDate?: string | null
  timeEntryIds?: string[]
  disbursementIds?: string[]
  createdBy?: string | null
  autoGenerated?: boolean
}

// Shared by the manual "Create Invoice" route (POST /api/accounttrack/invoices)
// and BillTrack's Stage 2 auto-generation cron — one code path for turning
// unbilled time entries/disbursements into an invoice + GL entry, so the two
// callers can never drift out of sync on the accounting logic.
export async function createInvoiceForMatter(input: CreateInvoiceInput) {
  const entryIds = input.timeEntryIds || []
  const disbIds = input.disbursementIds || []

  if (entryIds.length === 0 && disbIds.length === 0) {
    throw new InvoiceCreationError('Select at least one time entry or disbursement to bill')
  }

  const [entriesRes, disbursementsRes] = await Promise.all([
    entryIds.length > 0
      ? supabaseAdmin
          .from('time_entries')
          .select('id, amount')
          .eq('tenant_id', input.tenantId)
          .eq('matter_id', input.matterId)
          .eq('billable', true)
          .in('status', ['draft', 'submitted'])
          .in('id', entryIds)
      : Promise.resolve({ data: [] as { id: string; amount: number }[] }),
    disbIds.length > 0
      ? supabaseAdmin
          .from('disbursements')
          .select('id, amount')
          .eq('tenant_id', input.tenantId)
          .eq('matter_id', input.matterId)
          .eq('billed', false)
          .in('id', disbIds)
      : Promise.resolve({ data: [] as { id: string; amount: number }[] }),
  ])

  const entries = entriesRes.data || []
  const disbursements = disbursementsRes.data || []

  if (entries.length === 0 && disbursements.length === 0) {
    throw new InvoiceCreationError('None of the selected items are still unbilled')
  }

  const feesAmount = entries.reduce((sum, e) => sum + Number(e.amount || 0), 0)
  const disbursementsAmount = disbursements.reduce((sum, d) => sum + Number(d.amount || 0), 0)
  const invoiceNumber = await generateInvoiceNumber(input.tenantId)
  const invoiceDate = new Date().toISOString().split('T')[0]

  // currency follows the matter's billing_currency (falling back to the
  // tenant's base_currency).
  const [{ data: matter }, { data: org }] = await Promise.all([
    supabaseAdmin.from('matters').select('billing_currency').eq('id', input.matterId).eq('tenant_id', input.tenantId).single(),
    supabaseAdmin.from('organizations').select('base_currency').eq('id', input.tenantId).single(),
  ])
  const invoiceCurrency = matter?.billing_currency || org?.base_currency || 'NGN'
  const baseCurrency = org?.base_currency || 'NGN'

  try {
    await assertPeriodOpen(input.tenantId, invoiceDate)
  } catch (err) {
    if (err instanceof JournalPostingError) throw new InvoiceCreationError(err.message, 400)
    throw err
  }

  // The invoice (recognition of Accounts Receivable) is translated at the
  // spot rate as of the invoice date, applied uniformly to the fees/
  // disbursements split so the base-currency amounts still balance
  // exactly. Same-currency invoices get rate=1 with no DB lookup.
  let rate: number
  try {
    rate = await getExchangeRate(input.tenantId, invoiceCurrency, baseCurrency, invoiceDate)
  } catch (err) {
    if (err instanceof ExchangeRateError) throw new InvoiceCreationError(err.message, 400)
    throw err
  }
  const baseFeesAmount = feesAmount * rate
  const baseDisbursementsAmount = disbursementsAmount * rate
  const baseTotalAmount = baseFeesAmount + baseDisbursementsAmount

  const { data: invoice, error: invoiceError } = await supabaseAdmin
    .from('invoices')
    .insert({
      tenant_id: input.tenantId,
      matter_id: input.matterId,
      invoice_number: invoiceNumber,
      invoice_date: invoiceDate,
      due_date: input.dueDate || null,
      fees_amount: feesAmount,
      disbursements_amount: disbursementsAmount,
      total_amount: feesAmount + disbursementsAmount,
      currency: invoiceCurrency,
      base_currency_amount: baseTotalAmount,
      status: 'open',
      created_by: input.createdBy || null,
      auto_generated: input.autoGenerated || false,
    })
    .select()
    .single()

  if (invoiceError || !invoice) {
    throw new InvoiceCreationError(invoiceError?.message || 'Failed to create invoice', 500)
  }

  try {
    await postJournalEntry({
      tenantId: input.tenantId,
      entryDate: invoiceDate,
      description: `Invoice ${invoiceNumber} created`,
      sourceType: 'invoice_created',
      sourceId: invoice.id,
      createdBy: input.createdBy || invoice.created_by,
      lines: [
        { accountKey: 'accounts_receivable', matterId: input.matterId, debit: baseTotalAmount },
        { accountKey: 'fees_earned', matterId: input.matterId, credit: baseFeesAmount },
        { accountKey: 'client_costs_advanced', matterId: input.matterId, credit: baseDisbursementsAmount },
      ],
    })
  } catch (err) {
    throw new InvoiceCreationError(`Invoice created but GL posting failed: ${(err as Error).message}`, 500)
  }

  if (entries.length > 0) {
    await supabaseAdmin
      .from('time_entries')
      .update({ status: 'billed', invoice_id: invoice.id })
      .in('id', entries.map((e) => e.id))
  }

  if (disbursements.length > 0) {
    await supabaseAdmin
      .from('disbursements')
      .update({ billed: true, invoice_id: invoice.id })
      .in('id', disbursements.map((d) => d.id))
  }

  return invoice
}

export type ApplyInvoicePaymentInput = {
  tenantId: string
  invoice: { id: string; invoice_number: string; matter_id: string; currency: string | null; total_amount: number; paid_amount: number; base_currency_amount: number | null }
  paymentAmount: number
  entryDate: string
  createdBy: string
  // Defaults to the 'operating_cash' default account, preserving today's
  // exact behavior. Pass a raw id to deposit into a different cash
  // account (e.g. a custom "Petty Cash" account) -- Receive Payment's
  // reason for this parameter existing.
  cashAccountId?: string | null
  reference?: string | null
}

// Extracted verbatim from the invoices route's PATCH payment_amount
// branch so Receive Payment can reuse it. Caller must have already called
// assertPeriodOpen for entryDate -- not repeated here, since Receive
// Payment checks it once up front for the whole request.
export async function applyInvoicePayment(input: ApplyInvoicePaymentInput) {
  const { data: org } = await supabaseAdmin.from('organizations').select('base_currency').eq('id', input.tenantId).single()
  const baseCurrency = org?.base_currency || 'NGN'
  const invoiceCurrency = input.invoice.currency || baseCurrency

  const newPaid = Number(input.invoice.paid_amount || 0) + Number(input.paymentAmount)
  const updates = {
    paid_amount: newPaid,
    status: newPaid >= Number(input.invoice.total_amount || 0) ? 'paid' : 'partially_paid',
    updated_at: new Date().toISOString(),
  }

  const { data: updatedInvoice, error: updateError } = await supabaseAdmin
    .from('invoices')
    .update(updates)
    .eq('id', input.invoice.id)
    .eq('tenant_id', input.tenantId)
    .select()
    .single()

  if (updateError) throw new InvoiceCreationError(updateError.message, 500)

  // payment_amount is in the invoice's own currency. Convert to base
  // currency at the settlement date's rate -- the realized cash value. The
  // AR being settled is a proportional slice of what was originally
  // recognized at invoice creation (correctly handles partial payments
  // across multiple rates). Any difference is a realized FX gain or loss.
  let rate: number
  try {
    rate = await getExchangeRate(input.tenantId, invoiceCurrency, baseCurrency, input.entryDate)
  } catch (err) {
    if (err instanceof ExchangeRateError) throw new InvoiceCreationError(err.message, 400)
    throw err
  }
  const paymentBaseValue = Number(input.paymentAmount) * rate
  const totalAmount = Number(input.invoice.total_amount || 0)
  const originalArValue = totalAmount > 0
    ? (Number(input.paymentAmount) / totalAmount) * Number(input.invoice.base_currency_amount || 0)
    : Number(input.paymentAmount)
  const fxDiff = paymentBaseValue - originalArValue

  const cashTag = input.cashAccountId
    ? await tagOriginalAmountById(input.tenantId, input.cashAccountId, invoiceCurrency, Number(input.paymentAmount))
    : await tagOriginalAmount(input.tenantId, 'operating_cash', invoiceCurrency, Number(input.paymentAmount))

  const lines: JournalLineInput[] = [
    {
      ...(input.cashAccountId ? { accountId: input.cashAccountId } : { accountKey: 'operating_cash' }),
      matterId: input.invoice.matter_id,
      debit: paymentBaseValue,
      ...cashTag,
    },
    { accountKey: 'accounts_receivable', matterId: input.invoice.matter_id, credit: originalArValue },
  ]
  if (fxDiff > 0.005) {
    lines.push({ accountKey: 'fx_gain', matterId: input.invoice.matter_id, credit: fxDiff })
  } else if (fxDiff < -0.005) {
    lines.push({ accountKey: 'fx_loss', matterId: input.invoice.matter_id, debit: -fxDiff })
  }

  try {
    await postJournalEntry({
      tenantId: input.tenantId,
      entryDate: input.entryDate,
      description: `Payment received on invoice ${input.invoice.invoice_number}`,
      sourceType: 'invoice_payment',
      sourceId: input.invoice.id,
      createdBy: input.createdBy,
      reference: input.reference,
      lines,
    })
  } catch (err) {
    throw new InvoiceCreationError(`Invoice updated but GL posting failed: ${(err as Error).message}`, 500)
  }

  return updatedInvoice
}
