import { createClient } from '@supabase/supabase-js'
import { NextResponse } from 'next/server'
import { createInvoiceForMatter, InvoiceCreationError } from '@/lib/accounttrack/create-invoice'
import { sendInvoiceEmail, EmailSendError } from '@/lib/billtrack/send-email'
import { isMatterDueForAutoInvoice, isInvoiceDueForReminder } from '@/lib/billtrack/scheduling'

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// This loop can send a PDF-attached email per invoice across every
// billtrack-subscribed tenant in one run, so it gets more headroom than a
// single-invoice send route.
export const maxDuration = 120

// Vercel Cron triggers this with GET and, when CRON_SECRET is set as a
// project env var, automatically sends it as this bearer token — so this
// check alone is enough to reject any non-Vercel caller.
function isAuthorized(request: Request): boolean {
  const auth = request.headers.get('authorization')
  return !!process.env.CRON_SECRET && auth === `Bearer ${process.env.CRON_SECRET}`
}

// One daily pass per tenant with an active billtrack subscription:
//   1. auto-generate invoices for matters whose billing cycle is due today
//      and have unbilled time/disbursements
//   2. send the first notification for any invoice never sent
//   3. send a reminder for any open/unpaused invoice whose cadence elapsed
// Runs at daily-batch scale (dozens/hundreds of rows per tenant, once a
// day) rather than interactive request scale, so the per-matter/per-invoice
// queries below are deliberately not batched the way matter-register/
// lawyer-overview are — simplicity and testability win here over avoiding
// N+1, since there's no user waiting on this.
export async function GET(request: Request) {
  if (!isAuthorized(request)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const today = new Date()

  const { data: subs } = await supabaseAdmin
    .from('subscriptions')
    .select('tenant_id')
    .eq('module', 'billtrack')
    .eq('is_active', true)
  const tenantIds = [...new Set((subs || []).map((s) => s.tenant_id))]

  const summary = {
    autoInvoicesCreated: 0,
    autoInvoiceErrors: [] as { matterId: string; error: string }[],
    emailsSent: 0,
    emailErrors: [] as { invoiceId: string; error: string }[],
  }

  for (const tenantId of tenantIds) {
    const { data: matters } = await supabaseAdmin
      .from('matters')
      .select('id, billing_frequency, billing_anchor_day')
      .eq('tenant_id', tenantId)
      .eq('status', 'active')

    for (const matter of matters || []) {
      if (!isMatterDueForAutoInvoice(matter, today)) continue

      const [entriesRes, disbRes] = await Promise.all([
        supabaseAdmin
          .from('time_entries')
          .select('id')
          .eq('tenant_id', tenantId)
          .eq('matter_id', matter.id)
          .eq('billable', true)
          .in('status', ['draft', 'submitted']),
        supabaseAdmin
          .from('disbursements')
          .select('id')
          .eq('tenant_id', tenantId)
          .eq('matter_id', matter.id)
          .eq('billed', false),
      ])
      const entryIds = (entriesRes.data || []).map((e) => e.id)
      const disbIds = (disbRes.data || []).map((d) => d.id)
      if (entryIds.length === 0 && disbIds.length === 0) continue

      try {
        await createInvoiceForMatter({
          tenantId,
          matterId: matter.id,
          timeEntryIds: entryIds,
          disbursementIds: disbIds,
          autoGenerated: true,
        })
        summary.autoInvoicesCreated++
      } catch (err) {
        const message = err instanceof InvoiceCreationError ? err.message : (err as Error).message
        summary.autoInvoiceErrors.push({ matterId: matter.id, error: message })
      }
    }

    const { data: settings } = await supabaseAdmin
      .from('billtrack_settings')
      .select('reminder_cadence_days')
      .eq('tenant_id', tenantId)
      .maybeSingle()
    const cadenceDays = settings?.reminder_cadence_days ?? 7

    const { data: invoices } = await supabaseAdmin
      .from('invoices')
      .select('id, status, reminders_paused')
      .eq('tenant_id', tenantId)
      .in('status', ['open', 'partially_paid'])

    for (const invoice of invoices || []) {
      const { data: lastReminder } = await supabaseAdmin
        .from('invoice_reminders')
        .select('sent_at')
        .eq('invoice_id', invoice.id)
        .order('sent_at', { ascending: false })
        .limit(1)
        .maybeSingle()
      const lastSentAt = lastReminder?.sent_at ? new Date(lastReminder.sent_at) : null

      if (!isInvoiceDueForReminder(invoice, lastSentAt, cadenceDays, today)) continue

      try {
        await sendInvoiceEmail(tenantId, invoice.id, lastSentAt === null ? 'initial' : 'reminder')
        summary.emailsSent++
      } catch (err) {
        const message = err instanceof EmailSendError ? err.message : (err as Error).message
        summary.emailErrors.push({ invoiceId: invoice.id, error: message })
      }
    }
  }

  return NextResponse.json({ ok: true, ...summary })
}
